# Generated by Django 2.1 on 2018-08-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_of_prisoed_mosh', models.PositiveSmallIntegerField()),
                ('category', models.PositiveSmallIntegerField()),
                ('voltage', models.CharField(max_length=5)),
                ('chas0', models.FloatField()),
                ('chas1', models.FloatField()),
                ('chas2', models.FloatField()),
                ('chas3', models.FloatField()),
                ('chas4', models.FloatField()),
                ('chas5', models.FloatField()),
                ('chas6', models.FloatField()),
                ('chas7', models.FloatField()),
                ('chas8', models.FloatField()),
                ('chas9', models.FloatField()),
                ('chas10', models.FloatField()),
                ('chas11', models.FloatField()),
                ('chas12', models.FloatField()),
                ('chas13', models.FloatField()),
                ('chas14', models.FloatField()),
                ('chas15', models.FloatField()),
                ('chas16', models.FloatField()),
                ('chas17', models.FloatField()),
                ('chas18', models.FloatField()),
                ('chas19', models.FloatField()),
                ('chas20', models.FloatField()),
                ('chas21', models.FloatField()),
                ('chas22', models.FloatField()),
                ('chas23', models.FloatField()),
            ],
        ),
    ]
