# Generated by Django 2.1 on 2018-08-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakopitel', '0002_remove_price_voltage'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='title',
            field=models.TextField(default=1),
        ),
    ]
