# Generated by Django 2.1 on 2018-08-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakopitel', '0003_price_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='Stoimost_PG',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='price',
            name='Stoimost_PT',
            field=models.FloatField(default=0),
        ),
    ]
